package no.nav.poao_tilgang.api.dto.request

enum class PolicyId {
	NAV_ANSATT_TILGANG_TIL_EKSTERN_BRUKER_V1,
	NAV_ANSATT_TILGANG_TIL_EKSTERN_BRUKER_V2,
	NAV_ANSATT_TILGANG_TIL_MODIA_V1,
	EKSTERN_BRUKER_TILGANG_TIL_EKSTERN_BRUKER_V1,
}
