package no.nav.poao_tilgang.core.domain

enum class PolicyType(val type: String) {
	TILGANG_TIL_MODIA("TILGANG_TIL_MODIA"),
	TILGANG_TIL_SKJERMET_PERSON("TILGANG_TIL_SKJERMET_PERSON"),
	TILGANG_TIL_EKSTERN_PERSON("TILGANG_TIL_EKSTERN_PERSON"),
	TILGANG_TIL_STRENGT_FORTROLIG_BRUKER("TILGANG_TIL_STRENGT_FORTROLIG_BRUKER"),
	TILGANG_TIL_FORTROLIG_BRUKER("TILGANG_TIL_FORTROLIG_BRUKER"),
}

