package no.nav.poao_tilgang.domain

enum class DecisionReasonType(val reason: String) {
	PERMITTED("PERMITTED"),
	IKKE_MEDLEM_AV_AD_GRUPPE_SKJERMET_PERSON("IKKE_MEDLEM_AV_AD_GRUPPE_SKJERMET_PERSON"),
	IKKE_TILGANG_TIL_OPPFOLGINGSENHET("IKKE_TILGANG_TIL_OPPFOLGINGSENHET")
}
