package no.nav.poao_tilgang.domain

enum class Policy(val policy: String) {
    LESETILGANG_TIL_EKSTERN_BRUKER("LESETILGANG_TIL_EKSTERN_BRUKER"),
    SKRIVETILGANG_TIL_EKSTERN_BRUKER("SKRIVETILGANG_TIL_EKSTERN_BRUKER"),
    TILGANG_TIL_ENHET("TILGANG_TIL_ENHET"),
    TILGANG_TIL_KODE6("TILGANG_TIL_KODE6"),
    TILGANG_TIL_KODE7("TILGANG_TIL_KODE7"),
    TILGANG_TIL_SKJERMET_PERSON("TILGANG_TIL_SKJERMET_PERSON")
}
